name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Zestwear
            git pull origin main # Pull the latest changes
            npm install 
            npx prisma migrate deploy # Run database migrations
            npx prisma generate
            npm run build 
            pm2 restart next-app # Restart the app with zero downtime